In [2]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report
import joblib
import os
import ast

In [3]:
df = pd.read_csv("../data/1_Recipe_csv.csv")
df.head()

,recipe_title,category,subcategory,description,ingredients,directions,num_ingredients,num_steps
0,Air Fryer Potato Slices with Dipping Sauce,Air Fryer Recipes,Air Fryer Recipes,"These air fryer potato slices, served with a b...","[""3/4 cup ketchup"", ""1/2 cup beer"", ""1 tablesp...","[""Combine ketchup, beer, Worcestershire sauce,...",9,5
1,Gochujang Pork Belly Bites,Air Fryer Recipes,Air Fryer Recipes,These gochujang pork belly bites are sweet and...,"[""1 pound pork belly"", ""1/4 cup gochujang"", ""2...","[""Preheat an air fryer to 400 degrees F (200 d...",5,4
2,3-Ingredient Air Fryer Everything Bagel Chicke...,Air Fryer Recipes,Air Fryer Recipes,These 3-ingredient air fryer everything bagel ...,"[""1 \u00bc pounds chicken tenders"", ""1 tablesp...","[""Gather all ingredients. Preheat an air fryer...",3,4
3,Air Fryer Everything Bagel Chicken Cutlets,Air Fryer Recipes,Air Fryer Recipes,These air fryer everything bagel chicken cutle...,"[""4 chicken cutlets (about 1 pound total)"", ""s...","[""Preheat an air fryer to 400 degrees F (200 d...",9,9
4,Air Fryer Honey Sriracha Salmon Bites,Air Fryer Recipes,Air Fryer Recipes,These air fryer honey Sriracha salmon bites ar...,"[""1 tablespoon soy sauce"", ""1 tablespoon honey...","[""Preheat an air fryer to 400 degrees F (200 d...",5,5

In [4]:
df['ingredients'] = df['ingredients'].apply(ast.literal_eval)
df['ingredients_text'] = df['ingredients'].apply(lambda x: ' '.join(x))

In [5]:
df.head()

,recipe_title,category,subcategory,description,ingredients,directions,num_ingredients,num_steps,ingredients_text
0,Air Fryer Potato Slices with Dipping Sauce,Air Fryer Recipes,Air Fryer Recipes,"These air fryer potato slices, served with a b...","[3/4 cup ketchup, 1/2 cup beer, 1 tablespoon W...","[""Combine ketchup, beer, Worcestershire sauce,...",9,5,3/4 cup ketchup 1/2 cup beer 1 tablespoon Worc...
1,Gochujang Pork Belly Bites,Air Fryer Recipes,Air Fryer Recipes,These gochujang pork belly bites are sweet and...,"[1 pound pork belly, 1/4 cup gochujang, 2 tabl...","[""Preheat an air fryer to 400 degrees F (200 d...",5,4,1 pound pork belly 1/4 cup gochujang 2 tablesp...
2,3-Ingredient Air Fryer Everything Bagel Chicke...,Air Fryer Recipes,Air Fryer Recipes,These 3-ingredient air fryer everything bagel ...,"[1 ¼ pounds chicken tenders, 1 tablespoon oliv...","[""Gather all ingredients. Preheat an air fryer...",3,4,1 ¼ pounds chicken tenders 1 tablespoon olive ...
3,Air Fryer Everything Bagel Chicken Cutlets,Air Fryer Recipes,Air Fryer Recipes,These air fryer everything bagel chicken cutle...,"[4 chicken cutlets (about 1 pound total), salt...","[""Preheat an air fryer to 400 degrees F (200 d...",9,9,4 chicken cutlets (about 1 pound total) salt a...
4,Air Fryer Honey Sriracha Salmon Bites,Air Fryer Recipes,Air Fryer Recipes,These air fryer honey Sriracha salmon bites ar...,"[1 tablespoon soy sauce, 1 tablespoon honey, 1...","[""Preheat an air fryer to 400 degrees F (200 d...",5,5,1 tablespoon soy sauce 1 tablespoon honey 1 ta...

In [33]:
X=df['ingredients_text']
y=df['recipe_title']

In [34]:
vectorizer = TfidfVectorizer(stop_words='english', max_features=5000, min_df=5)
X_vec = vectorizer.fit_transform(X)

In [35]:
# X_vec.shape
# X_vec

In [36]:
X_train, X_test, y_train, y_test = train_test_split(X_vec, y, test_size=0.2, random_state=42)

In [37]:

from sklearn.naive_bayes import MultinomialNB

model = MultinomialNB()
model.fit(X_train, y_train)

MultinomialNB()

In [38]:

y_pred = model.predict(X_test)
print(classification_report(y_test, y_pred, zero_division=0))

c:\Users\k.hegde\Desktop\Learning_Projects\Recipe_Recommender\venv\Lib\site-packages\sklearn\metrics\_classification.py:98: UserWarning: The number of unique classes is greater than 50% of the number of samples. `y` could represent a regression problem, not a classification problem.
  type_true = type_of_target(y_true, input_name="y_true")
c:\Users\k.hegde\Desktop\Learning_Projects\Recipe_Recommender\venv\Lib\site-packages\sklearn\utils\multiclass.py:79: UserWarning: The number of unique classes is greater than 50% of the number of samples. `y` could represent a regression problem, not a classification problem.
  ys_types = set(type_of_target(x) for x in ys)
c:\Users\k.hegde\Desktop\Learning_Projects\Recipe_Recommender\venv\Lib\site-packages\sklearn\metrics\_classification.py:98: UserWarning: The number of unique classes is greater than 50% of the number of samples. `y` could represent a regression problem, not a classification problem.
  type_true = type_of_target(y_true, input_name="y_true")
c:\Users\k.hegde\Desktop\Learning_Projects\Recipe_Recommender\venv\Lib\site-packages\sklearn\utils\multiclass.py:79: UserWarning: The number of unique classes is greater than 50% of the number of samples. `y` could represent a regression problem, not a classification problem.
  ys_types = set(type_of_target(x) for x in ys)
c:\Users\k.hegde\Desktop\Learning_Projects\Recipe_Recommender\venv\Lib\site-packages\sklearn\metrics\_classification.py:98: UserWarning: The number of unique classes is greater than 50% of the number of samples. `y` could represent a regression problem, not a classification problem.
  type_true = type_of_target(y_true, input_name="y_true")
c:\Users\k.hegde\Desktop\Learning_Projects\Recipe_Recommender\venv\Lib\site-packages\sklearn\utils\multiclass.py:79: UserWarning: The number of unique classes is greater than 50% of the number of samples. `y` could represent a regression problem, not a classification problem.
  ys_types = set(type_of_target(x) for x in ys)
c:\Users\k.hegde\Desktop\Learning_Projects\Recipe_Recommender\venv\Lib\site-packages\sklearn\metrics\_classification.py:98: UserWarning: The number of unique classes is greater than 50% of the number of samples. `y` could represent a regression problem, not a classification problem.
  type_true = type_of_target(y_true, input_name="y_true")
c:\Users\k.hegde\Desktop\Learning_Projects\Recipe_Recommender\venv\Lib\site-packages\sklearn\utils\multiclass.py:79: UserWarning: The number of unique classes is greater than 50% of the number of samples. `y` could represent a regression problem, not a classification problem.
  ys_types = set(type_of_target(x) for x in ys)
c:\Users\k.hegde\Desktop\Learning_Projects\Recipe_Recommender\venv\Lib\site-packages\sklearn\metrics\_classification.py:98: UserWarning: The number of unique classes is greater than 50% of the number of samples. `y` could represent a regression problem, not a classification problem.
  type_true = type_of_target(y_true, input_name="y_true")
c:\Users\k.hegde\Desktop\Learning_Projects\Recipe_Recommender\venv\Lib\site-packages\sklearn\utils\multiclass.py:79: UserWarning: The number of unique classes is greater than 50% of the number of samples. `y` could represent a regression problem, not a classification problem.
  ys_types = set(type_of_target(x) for x in ys)
c:\Users\k.hegde\Desktop\Learning_Projects\Recipe_Recommender\venv\Lib\site-packages\sklearn\metrics\_classification.py:98: UserWarning: The number of unique classes is greater than 50% of the number of samples. `y` could represent a regression problem, not a classification problem.
  type_true = type_of_target(y_true, input_name="y_true")
c:\Users\k.hegde\Desktop\Learning_Projects\Recipe_Recommender\venv\Lib\site-packages\sklearn\utils\multiclass.py:79: UserWarning: The number of unique classes is greater than 50% of the number of samples. `y` could represent a regression problem, not a classification problem.
  ys_types = set(type_of_target(x) for x in ys)
c:\Users\k.hegde\Desktop\Learning_Projects\Recipe_Recommender\venv\Lib\site-packages\sklearn\metrics\_classification.py:98: UserWarning: The number of unique classes is greater than 50% of the number of samples. `y` could represent a regression problem, not a classification problem.
  type_true = type_of_target(y_true, input_name="y_true")
c:\Users\k.hegde\Desktop\Learning_Projects\Recipe_Recommender\venv\Lib\site-packages\sklearn\utils\multiclass.py:79: UserWarning: The number of unique classes is greater than 50% of the number of samples. `y` could represent a regression problem, not a classification problem.
  ys_types = set(type_of_target(x) for x in ys)
c:\Users\k.hegde\Desktop\Learning_Projects\Recipe_Recommender\venv\Lib\site-packages\sklearn\metrics\_classification.py:98: UserWarning: The number of unique classes is greater than 50% of the number of samples. `y` could represent a regression problem, not a classification problem.
  type_true = type_of_target(y_true, input_name="y_true")
c:\Users\k.hegde\Desktop\Learning_Projects\Recipe_Recommender\venv\Lib\site-packages\sklearn\utils\multiclass.py:79: UserWarning: The number of unique classes is greater than 50% of the number of samples. `y` could represent a regression problem, not a classification problem.
  ys_types = set(type_of_target(x) for x in ys)
c:\Users\k.hegde\Desktop\Learning_Projects\Recipe_Recommender\venv\Lib\site-packages\sklearn\metrics\_classification.py:98: UserWarning: The number of unique classes is greater than 50% of the number of samples. `y` could represent a regression problem, not a classification problem.
  type_true = type_of_target(y_true, input_name="y_true")
c:\Users\k.hegde\Desktop\Learning_Projects\Recipe_Recommender\venv\Lib\site-packages\sklearn\utils\multiclass.py:79: UserWarning: The number of unique classes is greater than 50% of the number of samples. `y` could represent a regression problem, not a classification problem.
  ys_types = set(type_of_target(x) for x in ys)

                                                                                                                     precision    recall  f1-score   support

                                                                                        "CranCrack" Cranberry Salad       0.00      0.00      0.00         1
                                                                                             "Everything" Seasoning       0.00      0.00      0.00         1
                                                                               "Horrible Hand" Ham and Cheese Board       0.00      0.00      0.00         1
                                                                  "Pretty Much a Piece of Heaven" Black Forest Cake       0.00      0.00      0.00         1
                                                                                        "Spa"ctacular Frozen Grapes       0.00      0.00      0.00         1
                                                                                         "Special" Roasted Potatoes       0.00      0.00      0.00         1
                                                                                                  "Tastee" Sandwich       0.00      0.00      0.00         2
                                                                                 "Thousand Layer" Chocolate Brioche       0.00      0.00      0.00         3
                                                                               'Got Some Crust' Macaroni and Cheese       0.00      0.00      0.00         1
                                                                          'Momma Made Em' Chicken and Sausage Gumbo       0.00      0.00      0.00         2
                                                            'So This Is What Heaven Tastes Like!' Cream Cheese Bars       0.00      0.00      0.00         1
                                                                                    'Unstuffed' Cabbage with a Kick       0.00      0.00      0.00         2
                                                                                         10 Pound Cheesecake Recipe       0.00      0.00      0.00         1
                                                                                       10-Minute Mushroom Carbonara       0.00      0.00      0.00         1
                                                                                               10-Minute Rice Cakes       0.00      0.00      0.00         1
                                                                                       10-Minute Tomato Basil Salad       0.00      0.00      0.00         1
                                                                     100% Whole Wheat Peanut Butter and Jelly Bread       0.00      0.00      0.00         1
                                               15-Minute Butter Gnocchi with Spicy Chili Crisp, Capers and Parmesan       0.00      0.00      0.00         1
                                                                       2-Ingredient Bacon-Wrapped Mozzarella Sticks       0.00      0.00      0.00         1
                                                                      2-Ingredient Dough Air Fryer Blueberry Bagels       0.00      0.00      0.00         2
                                                                                          2-Ingredient Dough Bagels       0.00      0.00      0.00         2
                                                                                    2-Ingredient Dough Garlic Knots       0.00      0.00      0.00         1
                                                                             2-Ingredient Pineapple Angel Food Cake       0.00      0.00      0.00         1
                                                                                          2-Ingredient Pumpkin Cake       0.00      0.00      0.00         1
                                                                    2-Ingredient Wheat-Free Banana Pancakes (Paleo)       0.00      0.00      0.00         2
                                                                          20-Minute Shrimp Fajitas Sheet Pan Dinner       0.00      0.00      0.00         1
                                                                                      3 Ingredient Sausage Biscuits       1.00      1.00      1.00         1
                                                                                                3-Cheese Enchiladas       0.00      0.00      0.00         1
                                                             3-Ingredient Air Fryer Everything Bagel Chicken Strips       0.00      0.00      0.00         1
                                                                                      3-Ingredient Baked Pork Chops       1.00      1.00      1.00         1
                                                                               3-Ingredient Japanese Potsticker Dip       0.00      0.00      0.00         1
                                                                                     3-Ingredient Limoncello Spritz       0.00      0.00      0.00         2
                                                                                            3-Ingredient Oreo Balls       0.00      0.00      0.00         1
                                                                                              3-Ingredient Pancakes       0.00      0.00      0.00         1
                                                                                      3-Ingredient Parmesan Cookies       0.00      0.00      0.00         1
                                                                                 3-Ingredient Peanut Butter Cookies       0.00      0.00      0.00         1
                                                                         3-Ingredient Peanut Butter Oatmeal Cookies       0.00      0.00      0.00         2
                                                                                    3-Ingredient Shortbread Cookies       0.00      0.00      0.00         1
                                                                                                     3-Minute Fudge       0.00      0.00      0.00         1
                                                                              4 Ingredient Air Fryer Pepper Poppers       0.00      0.00      0.00         1
                                                                                     4-Cheese Spinach-Artichoke Dip       0.00      0.00      0.00         1
                                                                                        4-Ingredient Bruschetta Dip       0.00      0.00      0.00         1
                                                                                     4-Ingredient Egg Avocado Toast       0.00      0.00      0.00         2
                                                                                   4-Ingredient Hamburger Casserole       0.00      0.00      0.00         2
                                                                            4-Ingredient Keto Peanut Butter Cookies       0.11      1.00      0.20         1
                                                                                      4-Ingredient Lemon Pound Cake       0.00      0.00      0.00         1
                                                                            4-Ingredient Nutter Butter Cookie Balls       1.00      1.00      1.00         1
                                                                                 4-Ingredient Pesto Tortellini Bake       1.00      1.00      1.00         1
                                                                                           4-Ingredient Potato Soup       0.00      0.00      0.00         1
                                                                            4-Ingredient Slow Cooker Cherry Cobbler       0.00      0.00      0.00         1
                                                                             4-Ingredient Slow Cooker Peach Cobbler       0.00      0.00      0.00         1
                                                                                4-Ingredient Strawberry Vinaigrette       0.00      0.00      0.00         1
                                                                                        4-Ingredient Teriyaki Sauce       0.00      0.00      0.00         1
                                                                                           4th of July Fruit Kabobs       0.00      0.00      0.00         1
                                                                                     5 Ingredient Chicken Taco Soup       0.00      0.00      0.00         2
                                                                                       5 Minute Microwave Cornbread       0.00      0.00      0.00         1
                                                                                                   5-Hour Beef Stew       0.00      0.00      0.00         1
                                                                                   5-Ingredient Breakfast Hand Pies       1.00      1.00      1.00         1
                                                                                    5-Ingredient No-Bake Cheesecake       0.00      0.00      0.00         1
                                                                       5-Ingredient Peanut Butter Chocolate Cookies       0.00      0.00      0.00         2
                                                                   5-Ingredient Peanut Butter Cottage Cheese Mousse       0.00      0.00      0.00         1
                                                                                                5-Layer Mexican Dip       0.00      0.00      0.00         1
                                                                                     6-Ingredient Ravioli Casserole       0.00      0.00      0.00         1
                                                                                                            7 and 7       0.00      0.00      0.00         1
                                                                                                        7-Layer Dip       0.00      0.00      0.00         1
                                                                                      90-Second Keto Bread in a Mug       0.00      0.00      0.00         3
                                                                                     A Farewell to Basil Fettuccine       0.00      0.00      0.00         1
                                                                                             A Number-One Egg Bread       0.00      0.00      0.00         1
                                                                                            A Pad Thai Worth Making       0.00      0.00      0.00         1
                                                                                                 A Plus Carrot Cake       0.00      0.00      0.00         2
                                                                                          A Scotsman's Shepherd Pie       0.00      0.00      0.00         2
                                                                                      A Simply Perfect Roast Turkey       1.00      1.00      1.00         1
                                                                              A Slice of Heaven (Baked Corned Beef)       0.00      0.00      0.00         1
                                                                                           A Very Moist Carrot Cake       0.00      0.00      0.00         1
                                               A to Z Everything-but-the-Kitchen-Sink Chocolate Chip Cookies Recipe       0.00      0.00      0.00         2
                                                                                             A-Number-1 Banana Cake       0.00      0.00      0.00         1
                                                                   ABC Pudding - Avocado, Banana, Chocolate Delight       0.00      0.00      0.00         2
                                                              AIP Breakfast Tapioca Porridge (Grain Free and Paleo)       0.00      0.00      0.00         1
                                                                                         Absolute Mexican Cornbread       0.00      0.00      0.00         1
                                                                                           Absolutely Best Brownies       1.00      1.00      1.00         1
                                                                         Absolutely the Best Chocolate Chip Cookies       0.00      0.00      0.00         1
                                                                                                          Acai Bowl       0.00      0.00      0.00         2
                                                                                                Acorn Candy Cookies       0.00      0.00      0.00         1
                                                                                                       Acorn Squash       0.18      1.00      0.31         2
                                                                                                Acorn Squash Butter       0.00      0.00      0.00         2
                                                                                             Acorn Squash Ice Cream       0.00      0.00      0.00         1
                                                                          Actually Delicious Buffalo Turkey Burgers       0.00      0.00      0.00         1
                                                                                                         Ada (Adai)       0.00      0.00      0.00         1
                                                                        Adas bil Hamod (Lebanese Lentil Lemon Soup)       0.00      0.00      0.00         1
                                                                                          Addictive Pumpkin Muffins       0.00      0.00      0.00         1
                                                                                                Adjarian Khachapuri       0.00      0.00      0.00         2
                                                                                                           Affogato       0.00      0.00      0.00         1
                                                                                                Afghani Kabli Pulao       0.00      0.00      0.00         1
                                                                                                      African Curry       0.00      0.00      0.00         1
                                                                                                African Peanut Soup       0.00      0.00      0.00         1
                                                                                Agua de Jamaica (Iced Hibiscus Tea)       0.00      0.00      0.00         2
                                                                                                   Agua de Valencia       0.00      0.00      0.00         1
                                                                                                          Aguachile       0.00      0.00      0.00         1
                                                                                                     Ahi Poke Salad       0.00      0.00      0.00         1
                                                                                                     Ahi Shoyu Poke       0.00      0.00      0.00         1
                                                                                                      Ahi Tuna Poke       0.00      0.00      0.00         1
                                                                                                  Air Fried Falafel       0.00      0.00      0.00         1
                                                                                          Air Fried Tossed Taquitos       1.00      1.00      1.00         2
                                                                                              Air Fryer Apple Crisp       0.00      0.00      0.00         1
                                                                        Air Fryer Apple Crisp with Oatmeal Streusel       0.00      0.00      0.00         1
                                                                                            Air Fryer Apple Crumble       0.00      0.00      0.00         1
                                                                                               Air Fryer Apple Pies       0.00      0.00      0.00         1
                                                                            Air Fryer Apple-Bacon French Toast Cups       0.00      0.00      0.00         1
                                                                                                 Air Fryer Arancini       0.00      0.00      0.00         1
                                                                                                Air Fryer Asparagus       0.00      0.00      0.00         1
                                                                                       Air Fryer BBQ Baby Back Ribs       0.00      0.00      0.00         1
                                                                                           Air Fryer Baby Back Ribs       0.00      0.00      0.00         1
                                                                                           Air Fryer Baked Potatoes       0.57      1.00      0.73         4
                                                                                           Air Fryer Bang Bang Tofu       0.00      0.00      0.00         1
                                                                                        Air Fryer Bang-Bang Chicken       0.00      0.00      0.00         1
                                                                                          Air Fryer Beef Tenderloin       0.00      0.00      0.00         2
                                                                                             Air Fryer Beef Wontons       0.00      0.00      0.00         1
                                                                                      Air Fryer Bell Pepper Poppers       0.00      0.00      0.00         1
                                                                                           Air Fryer Blooming Onion       0.00      0.00      0.00         1
                                                                                                 Air Fryer Broccoli       0.00      0.00      0.00         1
                                                                                            Air Fryer Buffalo Wings       0.00      0.00      0.00         2
                                                                                  Air Fryer Buffalo-Ranch Chickpeas       0.00      0.00      0.00         1
                                                                              Air Fryer Butternut Squash Home Fries       0.00      0.00      0.00         1
                                                                                                 Air Fryer Calamari       0.00      0.00      0.00         1
                                                                       Air Fryer Calzones With Two-Ingredient Dough       0.00      0.00      0.00         2
                                                                                    Air Fryer Cheesy Ranch Crackers       0.00      0.00      0.00         1

In [39]:
os.makedirs("../models", exist_ok=True)

joblib.dump(model, "../models/recipe_model.pkl")
joblib.dump(vectorizer, "../models/vectorizer.pkl")

print("✅ Model and vectorizer saved successfully!")

✅ Model and vectorizer saved successfully!